SELECT * FROM public.customer LIMIT 5;

--Q1. What is the total revenue generated by male vs. female customer?

SELECT gender, SUM(purchase_amount) as revenue
FROM public.customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM public.customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM public.customer)

--Q3. What are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) as "Average Product Review Rating"
FROM public.customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- When we loaded data from Jupyter into PostgreSQL,
-- the Review Rating column was treated as a decimal number.

-- PostgreSQL automatically stored it as DOUBLE PRECISION
-- (which is a floating-point data type).

-- The issue is that the ROUND() function does not always
-- work directly with DOUBLE PRECISION in the way we expect.

-- ROUND() works better with the NUMERIC data type.

-- We use ROUND() with DOUBLE PRECISION to limit the number of decimal places and make the result clean and readable (e.g., 4.56789 → 4.57), 
-- since floating-point numbers can have long or messy decimals.

-- So we convert (type cast) the column from DOUBLE PRECISION
-- to NUMERIC before applying ROUND().

-- Example:

--SELECT ROUND(review_rating::numeric, 2)
--FROM customer;

-- review_rating::numeric  → converts the column to NUMERIC
-- ROUND(..., 2)           → rounds the value to 2 decimal places

--Q4. Compare the average Purchase Amount between Standard and Express Shipping?

SELECT shipping_type,
ROUND(AVG(purchase_amount), 2)
FROM public.customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM public.customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with the discounts applied?

SELECT item_purchased,  -- Select the product name

ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
/ COUNT(*), 2) AS discount_rate  -- Calculate percentage of discounted purchases and round to 2 decimals

FROM public.customer  -- Use the customer table from public schema

GROUP BY item_purchased  -- Group data by product

ORDER BY discount_rate DESC  -- Sort from highest discount percentage to lowest

LIMIT 5;  -- Return only the top 5 products

-- Q7: Segment customers into New, Returning, and Loyal
-- based on their total number of previous purchases,
-- and count how many customers fall into each segment.

-- Business goal:
-- Customer segmentation helps businesses understand
-- customer loyalty and plan better marketing strategies.

-- Segmentation rules:
-- If previous purchases = 1 → Customer is "New"
-- If previous purchases between 2 and 10 → Customer is "Returning"
-- If previous purchases > 10 → Customer is "Loyal"

-- We will count how many customers fall into each category.

-- To make the query cleaner and easier to understand,
-- we will use a CTE (Common Table Expression).

-- A CTE is a temporary result set created using the WITH keyword.
-- It helps break complex queries into smaller, readable steps.

-- Step 1: Create a CTE (temporary table) called customer_type
WITH customer_type AS (

    -- Select customer ID and previous purchases
    SELECT 
        customer_id, 
        previous_purchases,

        -- Use CASE statement to classify customers
        CASE
            -- If purchased only once → New customer
            WHEN previous_purchases = 1 THEN 'New'

            -- If purchased between 2 and 10 times → Returning customer
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'

            -- If purchased more than 10 times → Loyal customer
            ELSE 'Loyal'
        END AS customer_segment  -- Name this new column customer_segment

    FROM public.customer  -- Take data from customer table
)

-- Step 2: Count how many customers fall into each segment
SELECT 
    customer_segment,  -- Show segment name
    COUNT(*) AS "Number of Customers per segment"  -- Count customers in each segment

FROM customer_type  -- Use the CTE created above

GROUP BY customer_segment  -- Group results by segment type

ORDER BY "Number of Customers per segment" DESC;

--Q8. What are the top 3 most purchased products within each category?

-- When ranking products in SQL, we can use three window functions:
-- 1) ROW_NUMBER()
-- 2) RANK()
-- 3) DENSE_RANK()

-- They all assign rankings, but they behave differently when there are ties
-- (i.e., when two products have the same value such as sales).

-- ROW_NUMBER()
-- - Assigns a unique number to each row.
-- - Does NOT handle ties specially.
-- - Even if two products have the same sales, they get different ranks.
-- - Use when you want a strict Top N list without shared ranks.

-- Example:
-- Sales: 100, 100, 90
-- ROW_NUMBER(): 1, 2, 3

-- RANK()
-- - Assigns the same rank to equal values.
-- - Skips the next rank after a tie.

-- Example:
-- Sales: 100, 100, 90
-- RANK(): 1, 1, 3  (Rank 2 is skipped)

-- DENSE_RANK()
-- - Assigns the same rank to equal values.
-- - Does NOT skip rank numbers after a tie.

-- Example:
-- Sales: 100, 100, 90
-- DENSE_RANK(): 1, 1, 2

-- Summary:
-- ROW_NUMBER() → Unique ranking (no ties).
-- RANK() → Ties allowed, gaps in ranking.
-- DENSE_RANK() → Ties allowed, no gaps in ranking.

-- Step 1: Create a CTE (temporary table) named item_counts
WITH item_counts AS (

    -- Select category and item name
    SELECT 
        category,
        item_purchased,

        -- Count how many times each item was purchased
        COUNT(customer_id) AS total_orders,

        -- Rank items within each category based on total orders
        ROW_NUMBER() OVER (
            PARTITION BY category              -- Restart ranking for each category
            ORDER BY COUNT(customer_id) DESC   -- Highest order count gets rank 1
        ) AS item_rank

    FROM public.customer  -- Use data from customer table

    -- Group by category and item to calculate counts correctly
    GROUP BY category, item_purchased
)

-- Step 2: Select results from the CTE
SELECT 
    item_rank,          -- Show ranking within category
    category,           -- Show category name
    item_purchased,     -- Show item name
    total_orders        -- Show total number of orders

FROM item_counts  -- Use the CTE created above

-- Keep only top 3 items per category
WHERE item_rank <= 3;

-- Why are we using ROW_NUMBER() instead of RANK() or DENSE_RANK()?

-- In our data, some items have the same total_orders value.
-- This means there are ties (equal numbers).

-- If we use RANK():
-- Items with the same total_orders will get the same rank.
-- For example:
-- Sunglasses and Belt might both get rank 2.
-- Also, Blouse and Pants might both get rank 1.
-- After a tie, RANK() skips the next number.

-- If we use DENSE_RANK():
-- Items with the same total_orders will also get the same rank.
-- However, DENSE_RANK() does NOT skip rank numbers.
-- But still, tied items share the same rank.

-- The problem:
-- We want exactly 3 distinct ranked items per category.
-- If two items share the same rank, we might end up
-- with fewer than 3 unique ranked positions.

-- That is why we use ROW_NUMBER().
-- ROW_NUMBER() always assigns a unique rank
-- even if total_orders are the same.

-- This guarantees:
-- Rank 1, Rank 2, Rank 3
-- Three different items per category.

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM public.customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM public.customer
GROUP BY age_group
ORDER BY total_revenue DESC;
